### ISSUE TITLE
pKa training data

### ISSUE THREAD

**Issue by freiburgermsu** [maranasgroup/dGPredictor#2]
Hello,

I am curious whether dGPredictor can be retrained with ~150,000 pKa values? My team believes that this will advance the accuracy and applicability your tool, and we can provide both the pKa values and coding effort to materialize this idea.

We are also interested to wrap dGPredictor into a KBase Application, which would uniquely provide thermochemical information that complements the array of biochemical Applications currently in [our catalogue](https://kbase.us/applist/). We can likewise assist the development of this effort, since we are co-developers of KBase.

I can meet anytime to elaborate these collaborative ideas, at your discretion.

Thank you :)
    Andrew

**Comment by Vik-u** [comment]
Hi Andrew, 

Thanks for reaching out. Sure, we can extend the dGPredictor framework to a bigger one. I agree that this will improve the accuracy and applicability of the tool. 

Dr. Christopher Henry also mentioned that about wrapping dGPredictor on KBase. It would be great to have the tool on KBase for easier user access. 

Let's meet over zoom to talk about the ideas that you have and we can come up with a plan to move forward on this. 

Feel free to mail me directly. Here is my PSU mail id- vuu10@psu.edu

Regards,
Vikas

**Comment by freiburgermsu** [comment]
I just sent an email :)
